plugin-prefix: "&b[&7CalculatorPlus&b]"

# Organized by command
messages:
 # Addition
  add: "/cp add <first number> <second number> etc"
  answer-add: "&aYour added numbers equal {answer}"
 # Subtraction
  subtract: "/cp subtract <first number> <second number> etc"
  answer-subtract: "&aYour subtracted numbers equal {answer}"
 # Multiplication
  multiply: "/cp multiply <first number> <second number> etc"
  answer-multiply: "&aYour multiplied numbers equal {answer}"
 # Division
  divide: "/cp divide <first number> <second number> etc"
  answer-divide: "&aYour divided numbers equal {answer}"
 # Quadratic
  quadratic: "/cp quadratic <a> <b> <c> (ax^2 + bx + c)"
  real-unequal: "Roots are real and unequal"
  real-equal: "Roots are real and equal"
  imaginary: "Roots are imaginary"
  root-one: "Root one is {root}"
  root-two: "Root two is {root}"
 # Pythagorean
  pythagorean: "/cp pythagorean <a> <b> (a^2 + b^2 = c^2)"
  answer-pythagorean: "Given A and B, C equals {answer}"
 # Error
  not-valid-number: "&cOne or more of your numbers was not valid. Please try again."
 # Tooltips
  solution: "&aSolution: "

