plugin-prefix: "&b[&7CalculatorPlus&b]"

# Tooltip hover colors
colors:
  signs: "&7"
  inputs: "&a"

# Organized by command
messages:
 # Addition
  add: "&a/cp add &7<#1> <#2> <#3> etc..."
  answer-add: "&aYour added numbers equal {answer}"
 # Subtraction
  subtract: "&a/cp subtract &7<#1> <#2> <#3> etc..."
  answer-subtract: "&aYour subtracted numbers equal {answer}"
 # Multiplication
  multiply: "&a/cp multiply &7<#1> <#2> <#3> etc..."
  answer-multiply: "&aYour multiplied numbers equal {answer}"
 # Division
  divide: "&a/cp divide &7<#1> <#2> <#3> etc..."
  answer-divide: "&aYour divided numbers equal {answer}"
 # Quadratic
  quadratic: "&a/cp quadratic &7<a> <b> <c>"
  real-unequal: "Roots are real and unequal"
  real-equal: "Roots are real and equal"
  imaginary: "Roots are imaginary"
  roots: "Roots are {root1} and {root2}"
 # Pythagorean
  pythagorean: "&a/cp pythagorean &7<a> <b>"
  answer-pythagorean: "Answer: {answer}"
 # Area
  area: "&a/cp area &7<shape> <length> <height>"
  area-answer: "The area of the {shape} is: {area}"
 # Error
  not-valid-number: "&cOne or more of your numbers was not valid. Please try again."
 # Tooltips
  solution: "&8Solution: "
  formula: "&7Formula: "

