plugin-prefix: "&b[&7CalculatorPlus&b]"

messages:
  add: "/cp add <first number> <second number> etc"
  subtract: "/cp subtract <first number> <second number> etc"
  multiply: "/cp multiply <first number> <second number> etc"
  divide: "/cp divide <first number> <second number> etc"
  not-valid-number: "&cOne or more of your numbers was not valid. Please try again."
  answer-add: "&aYour added numbers equal {answer}"
  answer-subtract: "&aYour subtracted numbers equal {answer}"
  answer-multiply: "&aYour multiplied numbers equal {answer}"
  answer-divide: "&aYour divided numbers equal {answer}"
